/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package parking.lot;

import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }

    // Parking parking;
    @Before
    public void initalize() {
       // parking = new ParkingServiceImpl();
    }

    @Test
    public void parkVehicle() {
//        Parking parking = new ParkingServiceImpl();
//        Vehicle vehicle = new Vehicle(Type);
//        int numberOfParkingSpotForMotorCycle = parking.getCountOfParkingSpot();
//        ParkingSpot spot = parking.park(vehicle);
//
//        Assert.assertEquals(numberOfParkingSpotForMotorCycle-1, parking.getCountOfParkingSpot);
//        Assert.assertEquals(spot.id, "123");
    }

    /***
     * This test will test against no. of spots remaining
     */
    @Test
    public void numberOfSpotsRemining () {
//        parking.reset();
//
//        parking.park(Vehicle1);
//        parking.park(Vehicle2);
//        parking.park(Vehicle3);

        // assert for spot for each vehicle type
    }
}
