/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package parkinglot;

import parkinglot.Domain.ParkingFloor;
import parkinglot.Domain.ParkingSlot;
import parkinglot.Domain.ParkingTicket;
import parkinglot.Domain.Payment;
import parkinglot.Domain.Vehicles.Car;
import parkinglot.Domain.Vehicles.MotorCycle;
import parkinglot.Domain.Vehicles.Van;
import parkinglot.Domain.Vehicles.Vehicle;
import parkinglot.Enums.ParkingSlotType;
import parkinglot.Interface.ParkingLotService;
import parkinglot.Service.ParkingLotServiceImpl;

import java.util.Arrays;

public class App {
    public static void main(String[] args) {
        ParkingLotService parkingLotService = new ParkingLotServiceImpl();

        // Create floor in parking lot

        ParkingSlot slot_0_1 = new ParkingSlot(ParkingSlotType.SMALL_SPOT);
        ParkingSlot slot_0_2 = new ParkingSlot(ParkingSlotType.SMALL_SPOT);
        ParkingSlot slot_0_3 = new ParkingSlot(ParkingSlotType.COMAPCT_SPOT);
        ParkingSlot slot_0_4 = new ParkingSlot(ParkingSlotType.COMAPCT_SPOT);
        ParkingSlot slot_0_5 = new ParkingSlot(ParkingSlotType.LARGE_SPOT);
        ParkingFloor floor1 = new ParkingFloor(0, Arrays.asList(slot_0_1, slot_0_2, slot_0_3, slot_0_4, slot_0_5));

        parkingLotService.addParkingFloor(floor1);

        Vehicle motorCycle = new MotorCycle("AB-1");
        Vehicle car = new Car("AB-2");
        Vehicle van = new Van("AB-3");

        ParkingTicket ticket = parkingLotService.parkVehicle(motorCycle);
        System.out.println(ticket);
        Payment payment = parkingLotService.unparkVehicle(motorCycle);
        System.out.println(payment);
    }
}
